name: mymind_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/bg/
    - assets/level/
    - assets/cards/
  fonts:
    # SFProText
    - family: Baloo2R
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
    - family: Baloo2M
      fonts:
        - asset: assets/fonts/Baloo2-Medium.ttf
    - family: Baloo2B
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf